// <auto-generated />
using System;
using HA.Adapter.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HA.Adapter.Persistence.Migrations.Application
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HA.Domain.Entities.Deal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Deals");

                    b.HasData(
                        new
                        {
                            Id = new Guid("75f1b113-b17a-4203-ba52-44f77fe67977"),
                            Description = "IRD Deal 123",
                            Name = "IRD"
                        },
                        new
                        {
                            Id = new Guid("a1bb0bb1-bd10-4de9-b03b-60486102f85b"),
                            Description = "IRD Deal 456",
                            Name = "IRD"
                        },
                        new
                        {
                            Id = new Guid("8e0ca577-3dd6-496a-9f44-9bf1a3d8c16b"),
                            Description = "IRD Deal 789",
                            Name = "IRD"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
